format = """
[](#f5c2e7)\
$username\
[](fg:#f5c2e7 bg:#cba6f7)\
$directory\
[](fg:#cba6f7 bg:#89b4fa)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#89b4fa bg:#a6e3a1)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
[ ](fg:#a6e3a1)\
"""

[username]
show_always = true
style_user = "bg:#f5c2e7 fg:#11111b"
style_root = "bg:#f5c2e7 fg:#11111b"
format = '[ 󰣚 ]($style)'
disabled = false
# Disable the blank line at the start of the prompt
# add_newline = true

[directory]
style = "fg:#11111b bg:#cba6f7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

[c]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[docker_context]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol$context ](fg:#11111b bg:#a6e3a1)]($style) $path'

[elixir]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[elm]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[git_branch]
symbol = " "
style = "fg:#11111b bg:#89b4fa"
format = '[[ $symbol$branch(:$remote_branch) ](fg:#11111b bg:#89b4fa)]($style)'

[git_status]
style = "fg:#11111b bg:#89b4fa"
format = '[[($all_status$ahead_behind )](fg:#11111b bg:#89b4fa)]($style)'

[git_metrics]
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
added_style = "fg:#178000 bg:#89b4fa"
deleted_style = "fg:#d20f39 bg:#89b4fa"
disabled = false

[golang]
symbol = " "
style = "fg:#11111b bg:##a6e3a1"
#format = '[[ $symbol ($version) ](fg:#11111b bg:#a6e3a1)]($style)'
format = '[[ $symbol](fg:#11111b bg:#a6e3a1)]($style)'

[haskell]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[nodejs]
symbol = ""
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol($version) ](fg:#11111b bg:#a6e3a1)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#11111b bg:#89b4fa"
format = '[[  $time ](fg:#11111b bg:#89b4fa)]($style)'
